[package]
name = "castelia-rtmp"
version = "0.1.0"
edition.workspace = true

[dependencies]
tokio.workspace = true
tracing = { workspace = true, features = ["log"] }
thiserror.workspace = true

[lints]
workspace = true
